defaults: &defaults
  working_directory: ~/app
  docker:
    - image: nikengp/node6:v0.4
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: NPM Install
          command: npm ci
      - run:
          name: Tests
          command: npm run test:ci


workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master